#PDF Extractor configuration
#Wed Jul 22 12:20:10 IST 2026
binMaster=D\:\\Exploritory Data \u2620\\BinMaster.xlsx
outputExcel=D\:\\PROJECTS\\PDFExtractor\\output\\Invoices.xlsx
pdfFolder=D\:\\TEST FOLDER\\PDFBox v2\\PDFBox\\PDFs
